### ISSUE TITLE
what the meaning of '4X' in the config file name R50_c4_4x ？

### ISSUE THREAD

**Issue by monsterlyg** [fcdl94/MMA#1]
do you mean the width is 4x times than the base R50 ? where can i change the time in config file, i didn't find the parameter. And the results in paper are under R50_4X ? but the other works are on R50_1X

**Comment by fcdl94** [comment]
Hello!
I used the same configuration of [FasterILOD](https://github.com/CanPeng123/Faster-ILOD), which is using the [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) library. 
Please, refer to these libraries for the backbone parameters. 

Talking about 4x, it refers to the batch size. 
The ResNet is the standard version, as you can see from the pretrained.
